name: BookStore

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: './server/.env'
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3001:3001